# Generated by Django 4.2.1 on 2023-05-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=100, verbose_name='Title')),
                ('organisation', models.CharField(max_length=100, verbose_name='Organisation')),
                ('nin', models.CharField(max_length=100, verbose_name='NIN')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('receivedTransport', models.BooleanField(default=False, verbose_name='Received Transport')),
                ('receivedLunch', models.BooleanField(default=False, verbose_name='Receieved Lunch')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('attendee', models.ManyToManyField(to='api.attendee')),
            ],
        ),
    ]
