# Generated by Django 4.2.1 on 2023-05-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_attendee_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='events',
            field=models.ManyToManyField(to='api.event'),
        ),
    ]
