# Generated by Django 4.2.1 on 2023-05-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_attendee_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='events',
            field=models.ManyToManyField(blank=True, to='api.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='api.attendee'),
        ),
    ]
