# Generated by Django 4.2.1 on 2023-05-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='arrivalTime',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Arrival Time'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
