# Generated by Django 4.2.1 on 2023-05-19 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='events',
        ),
        migrations.AddField(
            model_name='attendee',
            name='eventId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
