# Generated by Django 4.2.1 on 2023-05-19 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_attendee_events_attendee_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='eventId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='Given Name'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
