# Generated by Django 4.2.1 on 2023-05-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_client_dashboard_facilities_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='gender',
            field=models.CharField(max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
